/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corsan.conta.agua;

import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JTextField;

/**
 *
 * @author danie
 */
public class ContaDeAgua extends javax.swing.JFrame {

    /**
     * Creates new form ContaDeAgua
     */
    public ContaDeAgua() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfLeituraAtual = new javax.swing.JTextField();
        jtfLeituraAnteriorl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbCalcular = new javax.swing.JButton();
        jlValorDaConta = new javax.swing.JLabel();
        jlTaxa = new javax.swing.JLabel();
        jlValorLitro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Calculo de Água");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(550, 300));
        setMinimumSize(new java.awt.Dimension(550, 300));
        setPreferredSize(new java.awt.Dimension(550, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfLeituraAtual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jtfLeituraAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 175, -1));

        jtfLeituraAnteriorl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jtfLeituraAnteriorl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 175, -1));

        jLabel1.setText("Leitura Anterior:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setText("Valor a ser pago este mês:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setText("Sistema de Cálculo do valor de água a ser pago!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel4.setText("Leitura Atual:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("R$: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, 22));

        jbCalcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCalcular.setText("Calcular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jbCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jlValorDaConta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlValorDaConta.setText("0,00");
        getContentPane().add(jlValorDaConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 69, 22));

        jlTaxa.setText("Valor atual da Taxa: R$ 0,00");
        getContentPane().add(jlTaxa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jlValorLitro.setText("Valor do litro de água excedente a taxa: R$ 0,00");
        getContentPane().add(jlValorLitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    float taxaReais = 26.60f;
    BigDecimal taxaReaisAredondada = new BigDecimal(taxaReais).setScale(2, RoundingMode.HALF_EVEN);

    float aguaDentroDaTaxa = (20f / 6f) * 1000f;
    BigDecimal aguaDentroDaTaxaAredondada = new BigDecimal(aguaDentroDaTaxa).setScale(0, RoundingMode.HALF_EVEN);

//    float valorLitroExedente = (5.61f / 1000f);
    float valorLitroExedente = (9.761852f / 1000f);

    BigDecimal valorLitroExedenteAredondada = new BigDecimal(valorLitroExedente).setScale(5, RoundingMode.HALF_EVEN);
    
    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        int leituraAtual = Integer.parseInt(jtfLeituraAtual.getText());
        int leituraAnterior = Integer.parseInt(jtfLeituraAnteriorl.getText());
        int litros = leituraAtual - leituraAnterior;
            jlTaxa.setText("Valor atual da Taxa: R$" + taxaReaisAredondada.toString());
            jlValorLitro.setText("Valor aprox. do litro de água excedente a taxa: R$"+valorLitroExedenteAredondada);
        if (litros <= aguaDentroDaTaxa) {
//            jtfValorApagar.setText(taxaReaisAredondada.toString());
            jlValorDaConta.setText(taxaReaisAredondada.toString());

        } 
        else {
            float aguaExedente = litros - aguaDentroDaTaxa;
            float valorAgua = taxaReais + (aguaExedente * valorLitroExedente);
            BigDecimal valorAguaAredondada = new BigDecimal(valorAgua).setScale(2, RoundingMode.HALF_EVEN);
            jlValorDaConta.setText(valorAguaAredondada.toString());
//            jtfValorApagar.setText(valorAguaAredondada.toString());


        }


    }//GEN-LAST:event_jbCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaDeAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaDeAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaDeAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaDeAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContaDeAgua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JLabel jlTaxa;
    private javax.swing.JLabel jlValorDaConta;
    private javax.swing.JLabel jlValorLitro;
    private javax.swing.JTextField jtfLeituraAnteriorl;
    private javax.swing.JTextField jtfLeituraAtual;
    // End of variables declaration//GEN-END:variables
}
